// Generated by CoffeeScript 1.6.2
var $;

$ = jQuery;

$.fn.extend({
  lazyimg: function(options) {
    var $w, attrib, defaults, lazyimg, onWindowScrollEvent, retina, th;

    defaults = {
      threshold: 100
    };
    options = $.extend({}, defaults, options);
    $w = $(window);
    th = options.threshold;
    retina = window.devicePixelRatio > 1;
    attrib = retina ? "data-src-retina" : "data-src";
    onWindowScrollEvent = function() {
      clearTimeout(window._lazyimg_delay);
      return window._lazyimg_delay = setTimeout(lazyimg, 250);
    };
    lazyimg = function() {
      var $imgs, inview, wb, wt;

      $imgs = $("img.lazy");
      wt = $w.scrollTop();
      wb = wt + $w.height();
      inview = $imgs.filter(function() {
        var $e, eb, et;

        $e = $(this);
        et = $e.offset().top;
        eb = et + $e.height();
        return eb >= wt - th && et <= wb + th;
      });
      return inview.each(function() {
        var $this, source;

        $this = $(this);
        source = $this.attr(attrib);
        source = source || $this.attr("data-src");
        if (source) {
          $this.attr("src", source);
          return $this.removeClass("lazy");
        }
      });
    };
    $w.off('scroll.lazyimg');
    $w.on('scroll.lazyimg', onWindowScrollEvent);
    return onWindowScrollEvent();
  }
});
